# Generated by Django 3.0.7 on 2020-08-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.FileField(upload_to='media/profile'),
        ),
    ]
