# Generated by Django 3.0.7 on 2020-08-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFiles', '0002_auto_20200802_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
