# Generated by Django 3.0.7 on 2020-08-02 19:07

import crud.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFiles', '0003_auto_20200802_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='image',
        ),
        migrations.AddField(
            model_name='profileimage',
            name='file',
            field=models.FileField(default=23, storage=crud.storage_backends.PublicMediaStorage(), upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profileimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
